// Product data for all categories
const bakeryProducts = [
  { name: "Fresh Naan Bread", price: "$2.99", image: "/fresh-naan-bread.jpg", category: "Bakery" },
  { name: "Crispy Samosa", price: "$4.99", image: "/crispy-samosa.jpg", category: "Bakery" },
  { name: "Butter Paratha", price: "$3.49", image: "/layered-paratha.jpg", category: "Bakery" },
  { name: "Puffed Puri", price: "$2.49", image: "/puffed-puri-bread.jpg", category: "Bakery" },
  { name: "Aloo Tikki", price: "$3.99", image: "/aloo-tikki-potato-patty.jpg", category: "Bakery" },
  { name: "Kachori", price: "$4.49", image: "/kachori-fried-pastry.jpg", category: "Bakery" },
  { name: "Bhatura", price: "$3.99", image: "/bhatura-fried-bread.jpg", category: "Bakery" },
  { name: "Kulcha", price: "$2.99", image: "/kulcha-stuffed-bread.jpg", category: "Bakery" },
  { name: "Jalebi", price: "$5.99", image: "/jalebi-sweet-spiral.jpg", category: "Bakery" },
  { name: "Gulab Jamun", price: "$6.99", image: "/gulab-jamun-sweet-balls.jpg", category: "Bakery" },
  { name: "Rasgulla", price: "$6.49", image: "/rasgulla-spongy-dessert.jpg", category: "Bakery" },
  { name: "Barfi", price: "$7.99", image: "/barfi-milk-fudge.jpg", category: "Bakery" },
  { name: "Bread Loaf (White)", price: "$2.49", image: "/white-bread-loaf.png", category: "Bakery" },
  { name: "Bread Loaf (Brown)", price: "$2.99", image: "/brown-bread-loaf.jpg", category: "Bakery" },
  { name: "Pav Buns (8pc)", price: "$3.49", image: "/pav-buns.jpg", category: "Bakery" },
  { name: "Burger Buns (6pc)", price: "$3.99", image: "/burger-buns.jpg", category: "Bakery" },
  { name: "Rusks (Toast)", price: "$4.49", image: "/indian-rusks-toast.jpg", category: "Bakery" },
  { name: "Sponge Cake", price: "$8.99", image: "/sponge-cake.jpg", category: "Bakery" },
  { name: "Namkeen Mix", price: "$5.99", image: "/namkeen-mix.jpg", category: "Bakery" },
  { name: "Biscuits Assorted", price: "$4.99", image: "/indian-biscuits.jpg", category: "Bakery" },
]

const spicesProducts = [
  { name: "Cumin Seeds (Jeera)", price: "$4.99", image: "/cumin-seeds.jpg", category: "Spices" },
  { name: "Mustard Seeds (Rai)", price: "$3.99", image: "/mustard-seeds.png", category: "Spices" },
  { name: "Coriander Seeds (Dhania)", price: "$4.49", image: "/coriander-seeds.jpg", category: "Spices" },
  { name: "Fenugreek Seeds (Methi)", price: "$4.99", image: "/fenugreek-seeds.jpg", category: "Spices" },
  { name: "Green Cardamom (Choti Elaichi)", price: "$12.99", image: "/green-cardamom.jpg", category: "Spices" },
  { name: "Black Cardamom (Badi Elaichi)", price: "$14.99", image: "/black-cardamom.jpg", category: "Spices" },
  { name: "Cinnamon Sticks (Dalchini)", price: "$7.99", image: "/cinnamon-sticks.png", category: "Spices" },
  { name: "Cloves (Laung)", price: "$9.99", image: "/whole-cloves.jpg", category: "Spices" },
  { name: "Bay Leaf (Tej Patta)", price: "$3.49", image: "/bay-leaves.jpg", category: "Spices" },
  { name: "Black Pepper (Kali Mirch)", price: "$8.99", image: "/black-pepper-whole.jpg", category: "Spices" },
  { name: "Asafoetida (Hing)", price: "$11.99", image: "/asafoetida-hing.jpg", category: "Spices" },
  { name: "Fennel Seeds (Saunf)", price: "$4.49", image: "/fennel-seeds.jpg", category: "Spices" },
  { name: "Carom Seeds (Ajwain)", price: "$4.99", image: "/carom-seeds-ajwain.jpg", category: "Spices" },
  { name: "Nutmeg (Jaiphal)", price: "$13.99", image: "/nutmeg-whole.jpg", category: "Spices" },
  { name: "Mace (Javitri)", price: "$15.99", image: "/mace-spice.jpg", category: "Spices" },
  { name: "Star Anise", price: "$9.99", image: "/star-anise.jpg", category: "Spices" },
  { name: "Turmeric Powder (Haldi)", price: "$5.99", image: "/turmeric-powder.png", category: "Spices" },
  { name: "Red Chilli Powder (Lal Mirch)", price: "$5.49", image: "/red-chili-powder.jpg", category: "Spices" },
  { name: "Coriander Powder (Dhania)", price: "$4.49", image: "/coriander-powder.jpg", category: "Spices" },
  { name: "Cumin Powder (Jeera)", price: "$5.49", image: "/cumin-powder.jpg", category: "Spices" },
  { name: "Garam Masala", price: "$6.99", image: "/garam-masala-spice.jpg", category: "Spices" },
  { name: "Chaat Masala", price: "$5.99", image: "/chaat-masala.jpg", category: "Spices" },
  { name: "Kitchen King Masala", price: "$6.49", image: "/kitchen-king-masala.jpg", category: "Spices" },
  { name: "Curry Powder", price: "$5.99", image: "/curry-powder.jpg", category: "Spices" },
  { name: "Chana Masala", price: "$5.49", image: "/chana-masala-powder.jpg", category: "Spices" },
  { name: "Pav Bhaji Masala", price: "$5.99", image: "/pav-bhaji-masala.jpg", category: "Spices" },
  { name: "Amchoor (Dry Mango Powder)", price: "$6.49", image: "/amchoor-mango-powder.jpg", category: "Spices" },
  { name: "Dry Ginger Powder (Sonth)", price: "$5.99", image: "/dry-ginger-powder.jpg", category: "Spices" },
  { name: "Kashmiri Red Chilli", price: "$6.49", image: "/kashmiri-red-chili.jpg", category: "Spices" },
  { name: "Biryani Masala", price: "$6.99", image: "/biryani-masala.jpg", category: "Spices" },
  { name: "Tandoori Masala", price: "$6.49", image: "/tandoori-masala.jpg", category: "Spices" },
]

const vegetablesProducts = [
  { name: "Onion (Pyaaz)", price: "$1.99/lb", image: "/fresh-onions.jpg", category: "Vegetables" },
  { name: "Potato (Aloo)", price: "$1.49/lb", image: "/fresh-potatoes.jpg", category: "Vegetables" },
  { name: "Tomato (Tamatar)", price: "$2.49/lb", image: "/fresh-tomatoes.jpg", category: "Vegetables" },
  { name: "Ginger (Adrak)", price: "$3.99/lb", image: "/fresh-ginger-root.jpg", category: "Vegetables" },
  { name: "Garlic (Lahsun)", price: "$4.99/lb", image: "/fresh-garlic-bulbs.jpg", category: "Vegetables" },
  { name: "Green Chillies (Hari Mirch)", price: "$2.49/lb", image: "/green-chillies.jpg", category: "Vegetables" },
  { name: "Carrot (Gajar)", price: "$2.99/lb", image: "/fresh-carrots.jpg", category: "Vegetables" },
  { name: "Cauliflower (Gobi)", price: "$3.49/lb", image: "/fresh-cauliflower.jpg", category: "Vegetables" },
  { name: "Cabbage (Patta Gobi)", price: "$2.49/lb", image: "/fresh-cabbage.jpg", category: "Vegetables" },
  { name: "Green Peas (Matar)", price: "$3.99/lb", image: "/fresh-green-peas.jpg", category: "Vegetables" },
  { name: "Cucumber (Kheera)", price: "$2.49/lb", image: "/fresh-cucumber.jpg", category: "Vegetables" },
  {
    name: "Bell Peppers (Shimla Mirch)",
    price: "$3.99/lb",
    image: "/colorful-bell-peppers.jpg",
    category: "Vegetables",
  },
  { name: "Okra (Bhindi)", price: "$3.99/lb", image: "/fresh-okra.jpg", category: "Vegetables" },
  { name: "Bottle Gourd (Lauki)", price: "$2.99/lb", image: "/bottle-gourd.jpg", category: "Vegetables" },
  { name: "Bitter Gourd (Karela)", price: "$4.49/lb", image: "/bitter-gourd.png", category: "Vegetables" },
  { name: "Ridge Gourd (Turai)", price: "$3.49/lb", image: "/ridge-gourd.jpg", category: "Vegetables" },
  { name: "Snake Gourd (Chichinda)", price: "$3.99/lb", image: "/snake-gourd.jpg", category: "Vegetables" },
  { name: "Ash Gourd (Petha)", price: "$2.49/lb", image: "/ash-gourd.jpg", category: "Vegetables" },
  { name: "Indian Eggplant (Baingan)", price: "$2.99/lb", image: "/indian-eggplant.jpg", category: "Vegetables" },
  { name: "Spinach (Palak)", price: "$2.99/bunch", image: "/fresh-spinach.jpg", category: "Vegetables" },
  { name: "Fenugreek Leaves (Methi)", price: "$2.49/bunch", image: "/fenugreek-leaves.jpg", category: "Vegetables" },
  { name: "Coriander Leaves (Dhania)", price: "$1.99/bunch", image: "/fresh-coriander.jpg", category: "Vegetables" },
  { name: "Mint Leaves (Pudina)", price: "$1.99/bunch", image: "/fresh-mint-leaves.jpg", category: "Vegetables" },
  { name: "Curry Leaves (Kadhi Patta)", price: "$2.49/pack", image: "/fresh-curry-leaves.jpg", category: "Vegetables" },
  { name: "Drumstick (Moringa)", price: "$5.99/lb", image: "/drumstick-moringa.jpg", category: "Vegetables" },
  { name: "Cluster Beans (Gawar)", price: "$3.99/lb", image: "/cluster-beans.jpg", category: "Vegetables" },
  { name: "Taro Root (Arbi)", price: "$3.49/lb", image: "/taro-root.jpg", category: "Vegetables" },
  { name: "Radish (Mooli)", price: "$2.49/lb", image: "/fresh-radish.jpg", category: "Vegetables" },
  { name: "Turnip (Shalgam)", price: "$2.99/lb", image: "/fresh-turnip.jpg", category: "Vegetables" },
]

const fruitsProducts = [
  { name: "Alphonso Mango (Aam)", price: "$8.99/lb", image: "/alphonso-mango.jpg", category: "Fruits" },
  { name: "Banana (Kela)", price: "$1.99/lb", image: "/fresh-bananas.jpg", category: "Fruits" },
  { name: "Grapes (Angoor)", price: "$4.99/lb", image: "/fresh-grapes.jpg", category: "Fruits" },
  { name: "Apple (Seb)", price: "$3.99/lb", image: "/fresh-apples.jpg", category: "Fruits" },
  { name: "Guava (Amrood)", price: "$3.99/lb", image: "/fresh-guava.jpg", category: "Fruits" },
  { name: "Papaya (Papita)", price: "$2.99/lb", image: "/fresh-papaya.jpg", category: "Fruits" },
  { name: "Watermelon (Tarbooz)", price: "$0.99/lb", image: "/fresh-watermelon.jpg", category: "Fruits" },
  { name: "Custard Apple (Sharifa)", price: "$6.99/lb", image: "/custard-apple.jpg", category: "Fruits" },
  { name: "Sapota/Chikoo", price: "$4.99/lb", image: "/sapota-chikoo.jpg", category: "Fruits" },
  { name: "Pomegranate (Anar)", price: "$5.99/lb", image: "/ripe-pomegranate.jpg", category: "Fruits" },
  { name: "Indian Gooseberry (Amla)", price: "$4.49/lb", image: "/indian-gooseberry.jpg", category: "Fruits" },
  { name: "Jackfruit (Kathal)", price: "$3.99/lb", image: "/fresh-jackfruit.jpg", category: "Fruits" },
  { name: "Lychee", price: "$7.99/lb", image: "/fresh-lychee.jpg", category: "Fruits" },
  { name: "Dragon Fruit", price: "$5.49/lb", image: "/dragon-fruit.jpg", category: "Fruits" },
  { name: "Jamun (Blackberry)", price: "$5.99/lb", image: "/jamun-blackberry.jpg", category: "Fruits" },
  { name: "Orange (Santra)", price: "$3.49/lb", image: "/fresh-oranges.jpg", category: "Fruits" },
  { name: "Sweet Lime (Mosambi)", price: "$3.99/lb", image: "/sweet-lime.jpg", category: "Fruits" },
  { name: "Pineapple (Ananas)", price: "$4.99/each", image: "/fresh-pineapple.jpg", category: "Fruits" },
]

const dairyProducts = [
  { name: "Whole Milk (1 Gallon)", price: "$5.99", image: "/whole-milk-gallon.jpg", category: "Dairy" },
  { name: "Fresh Yogurt/Curd (Dahi)", price: "$3.99", image: "/fresh-yogurt.jpg", category: "Dairy" },
  { name: "Fresh Paneer", price: "$6.99", image: "/fresh-paneer.jpg", category: "Dairy" },
  { name: "Pure Desi Ghee (16oz)", price: "$14.99", image: "/pure-ghee.jpg", category: "Dairy" },
  { name: "Butter (Salted)", price: "$4.99", image: "/salted-butter.jpg", category: "Dairy" },
  { name: "Butter (Unsalted)", price: "$4.99", image: "/unsalted-butter.jpg", category: "Dairy" },
  { name: "Fresh Cream (Malai)", price: "$5.99", image: "/fresh-cream.jpg", category: "Dairy" },
  { name: "Buttermilk (Chaas)", price: "$2.99", image: "/buttermilk-chaas.jpg", category: "Dairy" },
  { name: "Mango Lassi", price: "$4.49", image: "/mango-lassi.png", category: "Dairy" },
  { name: "Sweet Lassi", price: "$3.99", image: "/sweet-lassi.jpg", category: "Dairy" },
  { name: "Khoya/Mawa", price: "$8.99", image: "/khoya-mawa.jpg", category: "Dairy" },
  { name: "Shrikhand", price: "$5.49", image: "/shrikhand-dessert.jpg", category: "Dairy" },
  { name: "Raita Mix", price: "$3.49", image: "/raita-yogurt.jpg", category: "Dairy" },
  { name: "Paneer Tikka (Ready)", price: "$9.99", image: "/paneer-tikka.jpg", category: "Dairy" },
  { name: "Cheese Slices", price: "$4.99", image: "/cheese-slices.jpg", category: "Dairy" },
]

const drinksProducts = [
  { name: "Masala Chai Tea Leaves", price: "$7.99", image: "/masala-chai.jpg", category: "Drinks" },
  { name: "Filter Coffee Powder", price: "$9.99", image: "/filter-coffee-powder.jpg", category: "Drinks" },
  { name: "Instant Coffee", price: "$6.99", image: "/instant-coffee.jpg", category: "Drinks" },
  { name: "Mango Lassi (Bottled)", price: "$4.49", image: "/mango-lassi.png", category: "Drinks" },
  { name: "Buttermilk/Chaas", price: "$2.99", image: "/buttermilk-chaas.jpg", category: "Drinks" },
  { name: "Rose Sherbet (Rooh Afza)", price: "$5.49", image: "/rose-milk-drink.jpg", category: "Drinks" },
  { name: "Mango Juice", price: "$4.99", image: "/mango-juice.png", category: "Drinks" },
  { name: "Guava Nectar", price: "$4.49", image: "/guava-nectar.jpg", category: "Drinks" },
  { name: "Litchi Juice", price: "$4.99", image: "/litchi-juice.jpg", category: "Drinks" },
  { name: "Fresh Coconut Water", price: "$3.99", image: "/refreshing-coconut-water.png", category: "Drinks" },
  { name: "Sugarcane Juice (Fresh)", price: "$4.99", image: "/sugarcane-juice.jpg", category: "Drinks" },
  { name: "Nimbu Pani Mix", price: "$3.49", image: "/nimbu-pani-mix.jpg", category: "Drinks" },
  { name: "Aam Panna Mix", price: "$4.99", image: "/aam-panna-mix.jpg", category: "Drinks" },
  { name: "Thandai Mix", price: "$6.99", image: "/thandai-mix.jpg", category: "Drinks" },
  { name: "Jaljeera Powder", price: "$3.99", image: "/jaljeera-powder.jpg", category: "Drinks" },
  { name: "Badam Milk Mix", price: "$8.99", image: "/badam-milk-mix.jpg", category: "Drinks" },
  { name: "Kesar Milk Mix", price: "$9.99", image: "/kesar-milk-mix.jpg", category: "Drinks" },
  { name: "Thums Up (Indian Cola)", price: "$2.49", image: "/thums-up-cola.jpg", category: "Drinks" },
  { name: "Limca (Lemon Soda)", price: "$2.49", image: "/limca-soda.jpg", category: "Drinks" },
]

const frozenProducts = [
  { name: "Frozen Paratha Pack (5pc)", price: "$8.99", image: "/frozen-paratha.jpg", category: "Frozen" },
  { name: "Frozen Aloo Paratha (5pc)", price: "$8.49", image: "/frozen-aloo-paratha.jpg", category: "Frozen" },
  { name: "Frozen Naan Pack (5pc)", price: "$7.99", image: "/frozen-naan-pack.jpg", category: "Frozen" },
  { name: "Frozen Samosa (12pc)", price: "$9.99", image: "/frozen-samosa.jpg", category: "Frozen" },
  { name: "Frozen Pakora Mix", price: "$6.99", image: "/frozen-pakora.jpg", category: "Frozen" },
  { name: "Frozen Green Peas", price: "$3.99", image: "/frozen-peas.jpg", category: "Frozen" },
  { name: "Frozen Spinach (Palak)", price: "$4.49", image: "/frozen-spinach.jpg", category: "Frozen" },
  { name: "Frozen Mixed Vegetables", price: "$4.99", image: "/frozen-mixed-vegetables.jpg", category: "Frozen" },
  { name: "Frozen Paneer Cubes", price: "$7.99", image: "/frozen-paneer-cubes.jpg", category: "Frozen" },
  { name: "Kulfi Ice Cream (Malai)", price: "$5.99", image: "/kulfi-ice-cream.jpg", category: "Frozen" },
  { name: "Kulfi Ice Cream (Mango)", price: "$5.99", image: "/mango-kulfi.jpg", category: "Frozen" },
  { name: "Kulfi Ice Cream (Pista)", price: "$6.49", image: "/pista-kulfi.jpg", category: "Frozen" },
  { name: "Frozen Chapati (10pc)", price: "$6.99", image: "/frozen-chapati.jpg", category: "Frozen" },
  { name: "Frozen Puri (20pc)", price: "$7.99", image: "/frozen-puri.jpg", category: "Frozen" },
  { name: "Frozen Bhatura (6pc)", price: "$8.99", image: "/frozen-bhatura.jpg", category: "Frozen" },
]

const dealsProducts = [
  {
    name: "Spice Bundle Pack",
    price: "$24.99",
    image: "/spice-bundle-pack.jpg",
    category: "Deals",
    originalPrice: "$34.99",
    discount: "30%",
    description:
      "Complete collection of essential Indian spices including turmeric, cumin, coriander, and garam masala.",
  },
  {
    name: "Fresh Produce Box",
    price: "$19.99",
    image: "/fresh-produce-box.jpg",
    category: "Deals",
    originalPrice: "$29.99",
    discount: "25%",
    description: "Fresh seasonal vegetables handpicked daily. Includes okra, bitter gourd, and leafy greens.",
  },
  {
    name: "Bakery Combo",
    price: "$14.99",
    image: "/bakery-combo-pack.jpg",
    category: "Deals",
    originalPrice: "$19.99",
    discount: "20%",
    description: "Freshly baked naan, paratha, samosas, and traditional Indian sweets.",
  },
  {
    name: "Dairy Essentials",
    price: "$22.99",
    image: "/dairy-essentials-pack.jpg",
    category: "Deals",
    originalPrice: "$29.99",
    discount: "25%",
    description: "Premium dairy products including paneer, ghee, fresh yogurt, and lassi.",
  },
  {
    name: "Snack Party Pack",
    price: "$29.99",
    image: "/snack-party-pack.jpg",
    category: "Deals",
    originalPrice: "$39.99",
    discount: "35%",
    description: "Assorted namkeen, biscuits, and traditional Indian snacks for parties.",
  },
  {
    name: "Breakfast Bundle",
    price: "$18.99",
    image: "/breakfast-bundle.jpg",
    category: "Deals",
    originalPrice: "$24.99",
    discount: "20%",
    description: "Everything you need for a perfect Indian breakfast including poha, upma mix, and more.",
  },
]
