export const bakeryProducts = [
  { name: "Fresh Naan Bread", price: "€2.99", image: "/fresh-indian-naan-bread.jpg", category: "Bakery" },
  {
    name: "Crispy Samosa",
    price: "€4.99",
    image: "/golden-crispy-indian-samosa.jpg",
    category: "Bakery",
  },
  { name: "Butter Paratha", price: "€3.49", image: "/buttery-layered-paratha.jpg", category: "Bakery" },
  { name: "Puffed Puri", price: "€2.49", image: "/puffed-golden-puri-bread.jpg", category: "Bakery" },
  { name: "Aloo Tikki", price: "€3.99", image: "/crispy-potato-aloo-tikki.jpg", category: "Bakery" },
  { name: "Kachori", price: "€4.49", image: "/stuffed-indian-kachori.jpg", category: "Bakery" },
  { name: "Bhatura", price: "€3.99", image: "/fluffy-bhatura-bread.jpg", category: "Bakery" },
  { name: "Kulcha", price: "€2.99", image: "/soft-indian-kulcha-bread.jpg", category: "Bakery" },
  { name: "Jalebi", price: "€5.99", image: "/orange-spiral-jalebi-sweet.jpg", category: "Bakery" },
  { name: "Gulab Jamun", price: "€6.99", image: "/round-gulab-jamun-dessert.jpg", category: "Bakery" },
  { name: "Rasgulla", price: "€6.49", image: "/white-spongy-rasgulla-sweet.jpg", category: "Bakery" },
  { name: "Barfi", price: "€7.99", image: "/indian-milk-barfi-sweet.jpg", category: "Bakery" },
  { name: "Bread Loaf (White)", price: "€2.49", image: "/white-bread-loaf.jpg", category: "Bakery" },
  { name: "Bread Loaf (Brown)", price: "€2.99", image: "/brown-wheat-bread-loaf.jpg", category: "Bakery" },
  { name: "Pav Buns (8pc)", price: "€3.49", image: "/soft-pav-buns.jpg", category: "Bakery" },
  { name: "Burger Buns (6pc)", price: "€3.99", image: "/burger-buns.jpg", category: "Bakery" },
  { name: "Rusks (Toast)", price: "€4.49", image: "/indian-rusks-toast.jpg", category: "Bakery" },
  { name: "Sponge Cake", price: "€8.99", image: "/sponge-cake.jpg", category: "Bakery" },
  { name: "Namkeen Mix", price: "€5.99", image: "/indian-namkeen-mix.jpg", category: "Bakery" },
  { name: "Biscuits Assorted", price: "€4.99", image: "/assorted-indian-biscuits.jpg", category: "Bakery" },
]

export const spicesProducts = [
  { name: "Cumin Seeds (Jeera)", price: "€4.99", image: "/cumin-seeds-jeera.jpg", category: "Spices" },
  { name: "Mustard Seeds (Rai)", price: "€3.99", image: "/mustard-seeds-rai.jpg", category: "Spices" },
  {
    name: "Coriander Seeds (Dhania)",
    price: "€4.49",
    image: "/coriander-seeds-dhania.jpg",
    category: "Spices",
  },
  {
    name: "Fenugreek Seeds (Methi)",
    price: "€4.99",
    image: "/fenugreek-seeds-methi.jpg",
    category: "Spices",
  },
  {
    name: "Green Cardamom (Choti Elaichi)",
    price: "€12.99",
    image: "/green-cardamom-pods.jpg",
    category: "Spices",
  },
  {
    name: "Black Cardamom (Badi Elaichi)",
    price: "€14.99",
    image: "/black-cardamom-pods.jpg",
    category: "Spices",
  },
  {
    name: "Cinnamon Sticks (Dalchini)",
    price: "€7.99",
    image: "/cinnamon-sticks-dalchini.jpg",
    category: "Spices",
  },
  { name: "Cloves (Laung)", price: "€9.99", image: "/cloves-laung.jpg", category: "Spices" },
  { name: "Bay Leaf (Tej Patta)", price: "€3.49", image: "/bay-leaf-tej-patta.jpg", category: "Spices" },
  {
    name: "Black Pepper (Kali Mirch)",
    price: "€8.99",
    image: "/black-pepper-kali-mirch.jpg",
    category: "Spices",
  },
  { name: "Asafoetida (Hing)", price: "€11.99", image: "/asafoetida-hing.jpg", category: "Spices" },
  { name: "Fennel Seeds (Saunf)", price: "€4.49", image: "/fennel-seeds-saunf.jpg", category: "Spices" },
  { name: "Carom Seeds (Ajwain)", price: "€4.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Nutmeg (Jaiphal)", price: "€13.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Mace (Javitri)", price: "€15.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Star Anise", price: "€9.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },

  {
    name: "Turmeric Powder (Haldi)",
    price: "€5.99",
    image: "/colorful-indian-spices-in-bowls-turmeric-cumin-cor.jpg",
    category: "Spices",
  },
  {
    name: "Red Chilli Powder (Lal Mirch)",
    price: "€5.49",
    image: "/fresh-green-chillies.jpg",
    category: "Spices",
  },
  {
    name: "Coriander Powder (Dhania)",
    price: "€4.49",
    image: "/coriander-seeds-dhania.jpg",
    category: "Spices",
  },
  { name: "Cumin Powder (Jeera)", price: "€5.49", image: "/cumin-seeds-jeera.jpg", category: "Spices" },
  { name: "Garam Masala", price: "€6.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Chaat Masala", price: "€5.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Kitchen King Masala", price: "€6.49", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Curry Powder", price: "€5.99", image: "/colorful-indian-spices-in-bowls-turmeric-cumin-cor.jpg", category: "Spices" },
  { name: "Chana Masala", price: "€5.49", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Pav Bhaji Masala", price: "€5.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  {
    name: "Amchoor (Dry Mango Powder)",
    price: "€6.49",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Spices",
  },
  {
    name: "Dry Ginger Powder (Sonth)",
    price: "€5.99",
    image: "/fresh-ginger-root.jpg",
    category: "Spices",
  },
  { name: "Kashmiri Red Chilli", price: "€6.49", image: "/fresh-green-chillies.jpg", category: "Spices" },
  { name: "Biryani Masala", price: "€6.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
  { name: "Tandoori Masala", price: "€6.49", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Spices" },
]

export const vegetablesProducts = [
  { name: "Onion (Pyaaz)", price: "€1.99/lb", image: "/fresh-red-onions.jpg", category: "Vegetables" },
  { name: "Potato (Aloo)", price: "€1.49/lb", image: "/brown-potatoes.jpg", category: "Vegetables" },
  {
    name: "Tomato (Tamatar)",
    price: "€2.49/lb",
    image: "/ripe-red-tomatoes.jpg",
    category: "Vegetables",
  },
  { name: "Ginger (Adrak)", price: "€3.99/lb", image: "/fresh-ginger-root.jpg", category: "Vegetables" },
  {
    name: "Garlic (Lahsun)",
    price: "€4.99/lb",
    image: "/garlic-bulbs.jpg",
    category: "Vegetables",
  },
  {
    name: "Green Chillies (Hari Mirch)",
    price: "€2.49/lb",
    image: "/fresh-green-chillies.jpg",
    category: "Vegetables",
  },
  { name: "Carrot (Gajar)", price: "€2.99/lb", image: "/orange-carrots.jpg", category: "Vegetables" },
  {
    name: "Cauliflower (Gobi)",
    price: "€3.49/lb",
    image: "/white-cauliflower-head.jpg",
    category: "Vegetables",
  },
  {
    name: "Cabbage (Patta Gobi)",
    price: "€2.49/lb",
    image: "/green-cabbage-head.jpg",
    category: "Vegetables",
  },
  {
    name: "Green Peas (Matar)",
    price: "€3.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Cucumber (Kheera)",
    price: "€2.49/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Bell Peppers (Shimla Mirch)",
    price: "€3.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },

  { name: "Okra (Bhindi)", price: "€3.99/lb", image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg", category: "Vegetables" },
  {
    name: "Bottle Gourd (Lauki)",
    price: "€2.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Bitter Gourd (Karela)",
    price: "€4.49/lb",
    image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg",
    category: "Vegetables",
  },
  {
    name: "Ridge Gourd (Turai)",
    price: "€3.49/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Snake Gourd (Chichinda)",
    price: "€3.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Ash Gourd (Petha)",
    price: "€2.49/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Indian Eggplant (Baingan)",
    price: "€2.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },

  {
    name: "Spinach (Palak)",
    price: "€2.99/bunch",
    image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg",
    category: "Vegetables",
  },
  {
    name: "Fenugreek Leaves (Methi)",
    price: "€2.49/bunch",
    image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg",
    category: "Vegetables",
  },
  {
    name: "Coriander Leaves (Dhania)",
    price: "€1.99/bunch",
    image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg",
    category: "Vegetables",
  },
  {
    name: "Mint Leaves (Pudina)",
    price: "€1.99/bunch",
    image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg",
    category: "Vegetables",
  },
  {
    name: "Curry Leaves (Kadhi Patta)",
    price: "€2.49/pack",
    image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg",
    category: "Vegetables",
  },

  {
    name: "Drumstick (Moringa)",
    price: "€5.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Cluster Beans (Gawar)",
    price: "€3.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  {
    name: "Taro Root (Arbi)",
    price: "€3.49/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
  { name: "Radish (Mooli)", price: "€2.49/lb", image: "/placeholder.jpg", category: "Vegetables" },
  {
    name: "Turnip (Shalgam)",
    price: "€2.99/lb",
    image: "/placeholder.jpg",
    category: "Vegetables",
  },
]

export const fruitsProducts = [
  {
    name: "Alphonso Mango (Aam)",
    price: "€8.99/lb",
    image: "/alphonso-mango.jpg",
    category: "Fruits",
  },
  { name: "Banana (Kela)", price: "€1.99/lb", image: "/yellow-ripe-bananas.jpg", category: "Fruits" },
  { name: "Grapes (Angoor)", price: "€4.99/lb", image: "/green-purple-grapes.jpg", category: "Fruits" },
  { name: "Apple (Seb)", price: "€3.99/lb", image: "/red-fresh-apples.jpg", category: "Fruits" },
  { name: "Guava (Amrood)", price: "€3.99/lb", image: "/green-guava-fruit.jpg", category: "Fruits" },
  { name: "Papaya (Papita)", price: "€2.99/lb", image: "/ripe-orange-papaya.jpg", category: "Fruits" },
  {
    name: "Watermelon (Tarbooz)",
    price: "€0.99/lb",
    image: "/red-watermelon-slice.jpg",
    category: "Fruits",
  },
  {
    name: "Custard Apple (Sharifa)",
    price: "€6.99/lb",
    image: "/green-custard-apple.jpg",
    category: "Fruits",
  },
  { name: "Sapota/Chikoo", price: "€4.99/lb", image: "/brown-sapota-chikoo-fruit.jpg", category: "Fruits" },
  { name: "Pomegranate (Anar)", price: "€5.99/lb", image: "/red-pomegranate-fruit.jpg", category: "Fruits" },
  {
    name: "Indian Gooseberry (Amla)",
    price: "€4.49/lb",
    image: "/green-amla-gooseberry.jpg",
    category: "Fruits",
  },
  { name: "Jackfruit (Kathal)", price: "€3.99/lb", image: "/large-jackfruit.jpg", category: "Fruits" },
  { name: "Lychee", price: "€7.99/lb", image: "/red-lychee-fruit.jpg", category: "Fruits" },
  { name: "Dragon Fruit", price: "€5.49/lb", image: "/pink-dragon-fruit.jpg", category: "Fruits" },
  { name: "Jamun (Blackberry)", price: "€5.99/lb", image: "/purple-jamun-berries.jpg", category: "Fruits" },
  { name: "Orange (Santra)", price: "€3.49/lb", image: "/fresh-orange-fruit.jpg", category: "Fruits" },
  {
    name: "Sweet Lime (Mosambi)",
    price: "€3.99/lb",
    image: "/green-sweet-lime-mosambi.jpg",
    category: "Fruits",
  },
  {
    name: "Pineapple (Ananas)",
    price: "€4.99/each",
    image: "/tropical-pineapple-fruit.jpg",
    category: "Fruits",
  },
]

export const dairyProducts = [
  { name: "Whole Milk (1 Gallon)", price: "€5.99", image: "/Whole-milk.jpg", category: "Dairy" },
  {
    name: "Fresh Yogurt/Curd (Dahi)",
    price: "€3.99",
    image: "/Fresh-Yogurt.jpg",
    category: "Dairy",
  },
  { name: "Fresh Paneer", price: "€6.99", image: "/Fresh-Paneer.jpg", category: "Dairy" },
  { name: "Pure Desi Ghee (16oz)", price: "€14.99", image: "/Pure-Desi-Ghee.jpg", category: "Dairy" },
  { name: "Butter (Salted)", price: "€4.99", image: "/Butter-Salted.jpg", category: "Dairy" },
  { name: "Butter (Unsalted)", price: "€4.99", image: "/Butter-Unsalted.jpg", category: "Dairy" },
  { name: "Fresh Cream (Malai)", price: "€5.99", image: "/Fresh-Cream.jpg", category: "Dairy" },
  { name: "Buttermilk (Chaas)", price: "€2.99", image: "/Buttermilk.jpg", category: "Dairy" },
  { name: "Mango Lassi", price: "€4.49", image: "/Mango-Lassi.jpg", category: "Dairy" },
  { name: "Sweet Lassi", price: "€3.99", image: "/Sweet-Lassi.jpg", category: "Dairy" },
  { name: "Khoya/Mawa", price: "€8.99", image: "/Khoya-Mawa.jpg", category: "Dairy" },
  { name: "Shrikhand", price: "€5.49", image: "/Shrikhand.jpg", category: "Dairy" },
  { name: "Raita Mix", price: "€3.49", image: "/Raita-Mix.jpg", category: "Dairy" },
  { name: "Paneer Tikka (Ready)", price: "€9.99", image: "/Paneer-Tikka.jpg", category: "Dairy" },
  { name: "Cheese Slices", price: "€4.99", image: "/Cheese-Slices.jpg", category: "Dairy" },
]

export const drinksProducts = [
  {
    name: "Masala Chai Tea Leaves",
    price: "€7.99",
    image: "/indian-beverages-mango-lassi-chai-masala-tea-refre.jpg",
    category: "Drinks",
  },
  { name: "Filter Coffee Powder", price: "€9.99", image: "/refreshing-beverages-juices-and-coffee-drinks.jpg", category: "Drinks" },
  { name: "Instant Coffee", price: "€6.99", image: "/refreshing-beverages-juices-and-coffee-drinks.jpg", category: "Drinks" },
  { name: "Mango Lassi (Bottled)", price: "€4.49", image: "/Mango-Lassi.jpg", category: "Drinks" },
  { name: "Buttermilk/Chaas", price: "€2.99", image: "/Buttermilk.jpg", category: "Drinks" },
  {
    name: "Rose Sherbet (Rooh Afza)",
    price: "€5.49",
    image: "/refreshing-beverages-juices-and-coffee-drinks.jpg",
    category: "Drinks",
  },
  { name: "Mango Juice", price: "€4.99", image: "/alphonso-mango.jpg", category: "Drinks" },
  { name: "Guava Nectar", price: "€4.49", image: "/green-guava-fruit.jpg", category: "Drinks" },
  { name: "Litchi Juice", price: "€4.99", image: "/red-lychee-fruit.jpg", category: "Drinks" },
  { name: "Fresh Coconut Water", price: "€3.99", image: "/refreshing-beverages-juices-and-coffee-drinks.jpg", category: "Drinks" },
  {
    name: "Sugarcane Juice (Fresh)",
    price: "€4.99",
    image: "/refreshing-beverages-juices-and-coffee-drinks.jpg",
    category: "Drinks",
  },
  { name: "Nimbu Pani Mix", price: "€3.49", image: "/green-sweet-lime-mosambi.jpg", category: "Drinks" },
  { name: "Aam Panna Mix", price: "€4.99", image: "/alphonso-mango.jpg", category: "Drinks" },
  { name: "Thandai Mix", price: "€6.99", image: "/indian-beverages-mango-lassi-chai-masala-tea-refre.jpg", category: "Drinks" },
  { name: "Jaljeera Powder", price: "€3.99", image: "/green-sweet-lime-mosambi.jpg", category: "Drinks" },
  { name: "Badam Milk Mix", price: "€8.99", image: "/Whole-milk.jpg", category: "Drinks" },
  { name: "Kesar Milk Mix", price: "€9.99", image: "/Whole-milk.jpg", category: "Drinks" },
  {
    name: "Thums Up (Indian Cola)",
    price: "€2.49",
    image: "/refreshing-beverages-juices-and-coffee-drinks.jpg",
    category: "Drinks",
  },
  { name: "Limca (Lemon Soda)", price: "€2.49", image: "/green-sweet-lime-mosambi.jpg", category: "Drinks" },
]

export const frozenProducts = [
  {
    name: "Frozen Paratha Pack (5pc)",
    price: "€8.99",
    image: "/frozen-indian-food-packages-parathas-samosas-ready.jpg",
    category: "Frozen",
  },
  {
    name: "Frozen Aloo Paratha (5pc)",
    price: "€8.49",
    image: "/frozen-indian-food-packages-parathas-samosas-ready.jpg",
    category: "Frozen",
  },
  {
    name: "Frozen Naan Pack (5pc)",
    price: "€7.99",
    image: "/fresh-indian-naan-bread.jpg",
    category: "Frozen",
  },
  { name: "Frozen Samosa (12pc)", price: "€9.99", image: "/frozen-indian-food-packages-parathas-samosas-ready.jpg", category: "Frozen" },
  { name: "Frozen Pakora Mix", price: "€6.99", image: "/frozen-indian-food-packages-parathas-samosas-ready.jpg", category: "Frozen" },
  { name: "Frozen Green Peas", price: "€3.99", image: "/fresh-vibrant-seasonal-indian-vegetables.jpg", category: "Frozen" },
  {
    name: "Frozen Spinach (Palak)",
    price: "€4.49",
    image: "/fresh-indian-vegetables-okra-bitter-gourd-leafy-gr.jpg",
    category: "Frozen",
  },
  {
    name: "Frozen Mixed Vegetables",
    price: "€4.99",
    image: "/fresh-vibrant-seasonal-indian-vegetables.jpg",
    category: "Frozen",
  },
  { name: "Frozen Paneer Cubes", price: "€7.99", image: "/Fresh-Paneer.jpg", category: "Frozen" },
  {
    name: "Kulfi Ice Cream (Malai)",
    price: "€5.99",
    image: "/frozen-meals-ice-cream-and-frozen-food-packaging.jpg",
    category: "Frozen",
  },
  {
    name: "Kulfi Ice Cream (Mango)",
    price: "€5.99",
    image: "/frozen-meals-ice-cream-and-frozen-food-packaging.jpg",
    category: "Frozen",
  },
  {
    name: "Kulfi Ice Cream (Pista)",
    price: "€6.49",
    image: "/frozen-meals-ice-cream-and-frozen-food-packaging.jpg",
    category: "Frozen",
  },
  { name: "Frozen Chapati (10pc)", price: "€6.99", image: "/buttery-layered-paratha.jpg", category: "Frozen" },
  { name: "Frozen Puri (20pc)", price: "€7.99", image: "/puffed-golden-puri-bread.jpg", category: "Frozen" },
  { name: "Frozen Bhatura (6pc)", price: "€8.99", image: "/fluffy-bhatura-bread.jpg", category: "Frozen" },
]

export const riceProducts = [
  {
    name: "Basmati Rice (Aged) 10lb",
    price: "€24.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
  {
    name: "Basmati Rice (Sella) 10lb",
    price: "€22.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
  { name: "Brown Basmati Rice 5lb", price: "€14.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Rice" },
  { name: "Sona Masoori Rice 10lb", price: "€18.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Rice" },
  { name: "Idli Rice 5lb", price: "€12.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Rice" },
  {
    name: "Poha (Flattened Rice) 2lb",
    price: "€5.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
  { name: "Vermicelli (Semiya) 1lb", price: "€3.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Rice" },
  {
    name: "Broken Wheat (Dalia) 2lb",
    price: "€6.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
  {
    name: "Jasmine Rice 5lb",
    price: "€15.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
  {
    name: "Red Rice 5lb",
    price: "€16.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
  {
    name: "Black Rice 2lb",
    price: "€18.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
  {
    name: "Sticky Rice (Glutinous) 2lb",
    price: "€7.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Rice",
  },
]

export const floursProducts = [
  {
    name: "Wheat Flour (Atta) 10lb",
    price: "€12.99",
    image: "/brown-wheat-bread-loaf.jpg",
    category: "Flours",
  },
  {
    name: "Besan (Gram Flour) 4lb",
    price: "€8.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  {
    name: "Maida (All-Purpose) 5lb",
    price: "€7.99",
    image: "/white-bread-loaf.jpg",
    category: "Flours",
  },
  {
    name: "Sooji/Rava (Semolina) 2lb",
    price: "€5.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  { name: "Rice Flour 2lb", price: "€6.49", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Flours" },
  {
    name: "Ragi Flour (Finger Millet) 2lb",
    price: "€7.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  {
    name: "Bajra Flour (Pearl Millet) 2lb",
    price: "€6.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  {
    name: "Jowar Flour (Sorghum) 2lb",
    price: "€6.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  {
    name: "Corn Flour (Makki) 2lb",
    price: "€5.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  {
    name: "Chickpea Flour (Besan Fine) 2lb",
    price: "€6.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  {
    name: "Multigrain Flour Mix 5lb",
    price: "€14.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
  {
    name: "Buckwheat Flour 2lb",
    price: "€8.99",
    image: "/colorful-exotic-indian-spices-in-bowls.jpg",
    category: "Flours",
  },
]

export const dalsProducts = [
  { name: "Toor Dal (Arhar) 4lb", price: "€9.99", image: "/fresh-vibrant-seasonal-indian-vegetables.jpg", category: "Dals" },
  { name: "Moong Dal (Split) 4lb", price: "€8.99", image: "/fresh-vibrant-seasonal-indian-vegetables.jpg", category: "Dals" },
  { name: "Chana Dal 4lb", price: "€7.99", image: "/fresh-vibrant-seasonal-indian-vegetables.jpg", category: "Dals" },
  { name: "Urad Dal (Split) 4lb", price: "€9.49", image: "/fresh-vibrant-seasonal-indian-vegetables.jpg", category: "Dals" },
  {
    name: "Urad Dal (Whole Black) 4lb",
    price: "€10.99",
    image: "/fresh-vibrant-seasonal-indian-vegetables.jpg",
    category: "Dals",
  },
  {
    name: "Masoor Dal (Red Lentils) 4lb",
    price: "€7.99",
    image: "/fresh-vibrant-seasonal-indian-vegetables.jpg",
    category: "Dals",
  },
  {
    name: "Rajma (Kidney Beans) 4lb",
    price: "€8.99",
    image: "/fresh-vibrant-seasonal-indian-vegetables.jpg",
    category: "Dals",
  },
  {
    name: "Kabuli Chana (Chickpeas) 4lb",
    price: "€8.49",
    image: "/fresh-vibrant-seasonal-indian-vegetables.jpg",
    category: "Dals",
  },
  {
    name: "Lobia (Black-eyed Peas) 2lb",
    price: "€5.99",
    image: "/fresh-vibrant-seasonal-indian-vegetables.jpg",
    category: "Dals",
  },
  {
    name: "Moong Dal (Whole Green) 4lb",
    price: "€9.99",
    image: "/fresh-vibrant-seasonal-indian-vegetables.jpg",
    category: "Dals",
  },
]

export const oilsProducts = [
  { name: "Pure Desi Ghee 32oz", price: "€24.99", image: "/placeholder.svg?height=400&width=400", category: "Oils" },
  { name: "Mustard Oil 1L", price: "€12.99", image: "/placeholder.svg?height=400&width=400", category: "Oils" },
  { name: "Sesame Oil 500ml", price: "€9.99", image: "/placeholder.svg?height=400&width=400", category: "Oils" },
  { name: "Groundnut Oil 1L", price: "€11.99", image: "/placeholder.svg?height=400&width=400", category: "Oils" },
  { name: "Coconut Oil 500ml", price: "€10.99", image: "/placeholder.svg?height=400&width=400", category: "Oils" },
  { name: "Sunflower Oil 1L", price: "€8.99", image: "/placeholder.svg?height=400&width=400", category: "Oils" },
  { name: "Vegetable Oil 1L", price: "€7.99", image: "/placeholder.svg?height=400&width=400", category: "Oils" },
]

export const dealsProducts = [
  { name: "Spice Bundle Pack", price: "€24.99", image: "/colorful-exotic-indian-spices-in-bowls.jpg", category: "Deals" },
  { name: "Fresh Produce Box", price: "€19.99", image: "/fresh-vibrant-seasonal-indian-vegetables.jpg", category: "Deals" },
  { name: "Bakery Combo", price: "€14.99", image: "/fresh-indian-bakery-with-naan-bread-samosas-and-tr.jpg", category: "Deals" },
  { name: "Dairy Essentials", price: "€22.99", image: "/indian-dairy-products-paneer-ghee-yogurt-lassi-mil.jpg", category: "Deals" },
  { name: "Snack Party Pack", price: "€29.99", image: "/indian-namkeen-mix.jpg", category: "Deals" },
  { name: "Breakfast Bundle", price: "€18.99", image: "/fresh-indian-bakery-with-naan-bread-samosas-and-tr.jpg", category: "Deals" },
  { name: "Dal Combo (5 types)", price: "€39.99", image: "/special-offers-discount-sale-indian-grocery-produc.jpg", category: "Deals" },
  { name: "Rice Variety Pack", price: "€44.99", image: "/special-offers-discount-sale-indian-grocery-produc.jpg", category: "Deals" },
  { name: "Flour Essentials", price: "€32.99", image: "/special-offers-discount-sale-indian-grocery-produc.jpg", category: "Deals" },
  { name: "Cooking Oil Bundle", price: "€49.99", image: "/special-offers-discount-sale-indian-grocery-produc.jpg", category: "Deals" },
]

export const allProducts = {
  bakery: bakeryProducts,
  spices: spicesProducts,
  vegetables: vegetablesProducts,
  fruits: fruitsProducts,
  dairy: dairyProducts,
  drinks: drinksProducts,
  frozen: frozenProducts,
  rice: riceProducts,
  flours: floursProducts,
  dals: dalsProducts,
  oils: oilsProducts,
  deals: dealsProducts,
}
